### ISSUE TITLE
cannot install on Laravel 6.18

### ISSUE THREAD

**Issue by omidMolaverdi** [freearhey/laravel-face-detection#2]
Please can you help?

**Comment by freearhey** [comment]
Unfortunately, the package currently only supports Laravel 7 versions. But I will try to add support for Laravel 6 as soon as I have some free time.

**Comment by omidMolaverdi** [comment]
@freearhey  thanks.

**Comment by omidMolaverdi** [comment]
Hi,
Hope that I am not disturbing you. Is there any update on this?

**Comment by freearhey** [comment]
I'm sorry, but after studying the question, I decided that supporting earlier versions of Laravel would be very time-consuming. I hope this is not too critical for your project and you will eventually be able to upgrade to the latest version of Laravel or find a working alternative.
