### ISSUE TITLE
Unknown Driver Type

### ISSUE THREAD

**Issue by rindibudiaramdhan** [freearhey/laravel-face-detection#7]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/19951241/175961810-1933f875-3b36-46a3-b9c4-0ea418ebf4e8.png">

**Comment by rindibudiaramdhan** [comment]
i got error like this. even config it to each driver that mention in config file.

**Comment by freearhey** [comment]
did you run the command: `php artisan vendor:publish` ?

https://github.com/freearhey/laravel-face-detection#installation

**Comment by freearhey** [comment]
to make the error go away, run the command: `php artisan vendor:publish`.

https://github.com/freearhey/laravel-face-detection#installation
