### ISSUE TITLE
Failing to install on laravel Framework 9.52.4

### ISSUE THREAD

**Issue by Tumi-D** [freearhey/laravel-face-detection#8]
![image](https://user-images.githubusercontent.com/14878778/224543481-4b09d6fb-0090-4f17-9145-4333842b0d41.png)

**Comment by Tumi-D** [comment]
![image](https://user-images.githubusercontent.com/14878778/224543481-4b09d6fb-0090-4f17-9145-4333842b0d41.png)

**Comment by ganeshrahul** [comment]
> ![image](https://user-images.githubusercontent.com/14878778/224543481-4b09d6fb-0090-4f17-9145-4333842b0d41.png)

Same error for me

**Comment by freearhey** [comment]
Fixed in `v1.4.0`
